### PR TITLE
Count selectors instead of rules as a limit for IE

### PR DESCRIPTION
**Pull request by kaelig**
Free internet explorer

### CODE REVIEW

**Comment by kaelig** [comment]
Ping :)

**Comment by joekukish** [comment]
+1 for this. This is actually the IE limitation

**Comment by dwabyick** [comment]
+1 for this!

**Comment by phamann** [comment]
Apologies for ignoring this! Thank you @kaelig for fixing this :wink: 

I will bump the version number to `0.1.2` and publish to npm.

**Comment by misterbrownlee** [comment]
Booyah... thanks @kaelig for the fix! Nice IE badge BTW :)

**Pull request merged**
